### PR TITLE
YOLO

### PR DESCRIPTION
**Pull request by bion**

### CODE REVIEW

**Comment by bion** [comment]
from [the docs](https://developers.google.com/image-search/v1/jsondevguide)

> Specifies the search safety level, which may be one of the following:
> 
>     safe=active enables the highest level of safe search filtering.
>     safe=moderate enables moderate safe search filtering (default).
>     safe=off disables safe search filtering.

**Comment by ohwillie** [comment]
oh my god

**Comment by ohwillie** [comment]
:+1: :+1: :+1:

**Comment by ptmccarthy** [comment]
what have you unleashed

**Comment by blucia0a** [comment]
lets just get those changes made.  I have some fisting gifs I really want
you guys to see.

**Comment by dbalatero** [comment]
what have i done

**Comment by bion** [comment]
WHAT HAVE WE DONE

**Comment by ptmccarthy** [comment]
abort abort

**Comment by heatherm** [comment]
amazing.

**Pull request merged**
